name: Build & Publish to PyPI

on:
  workflow_run:
    workflows: [Publish Executables]
    types: [completed]
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup the Python Environment
        uses: Qwerty-133/python-setup@v1
        with:
          python-version: 3.11
          skip-pre-commit: true
          use-cache: false

      - name: Publish
        run: >
          poetry publish --build --no-interaction
          --username __token__ --password ${{ secrets.PYPI_TOKEN }}
